#!/usr/bin/python
from Scanner import Scanner
import sys
import os

def main():
    num_args = len(sys.argv)-1
    try:
        if num_args == 0:
            sys.stderr.write("Error: not enough arguments\n")
        if num_args > 2:
            sys.stderr.write("Error: too many arguments\n")

        if sys.argv[1][1] == 's':
            if num_args == 1:
                input_string = sys.stdin.read()
                s = Scanner(input_string)
                s.all()
            elif num_args == 2:
                # read from file
                if os.path.isfile(sys.argv[2]):
                    f = open(sys.argv[2], 'r')
                    input_line = ""
                    for line in f:
                        input_line += line
                    s = Scanner(input_line)
                    s.all()
                    f.close()
                else:
                    sys.stderr.write("error: file \"{0}\" not found\n".format(sys.argv[2]))
        elif sys.argv[1][1] == 'c':
            sys.stderr.write("Error: invalid option\n")
        elif sys.argv[1][1] == 't':
            sys.stderr.write("Error: invalid option\n")
        elif sys.argv[1][1] == 'a':
            sys.stderr.write("Error: invalid option\n")
        elif sys.argv[1][1] == 'i':
            sys.stderr.write("Error: invalid option\n")
        else:
            sys.stderr.write("Error: invalid option\n")

    except Exception as e:
        pass
main()